### ISSUE TITLE
indicate what a proper and improper response is for ssh-agent

### ISSUE THREAD

**Issue by esteinborn** [justinlevi/drupal-vm-config#3]
https://github.com/justinlevi/drupal-vm-config#3-below-is-my-personal-fav-because-it-fires-when-i-open-cmder

I'm not sure what I should be seeing or not seeing when I type in `ssh-agent`

**Comment by justinlevi** [comment]
I _think_ you're just looking for anything but an error message. I'll add that as a comment though.
